[buildPlans.pataha]
family = "PATAHA"
spacing = "normal"
serifs = "sans"

  [buildPlans.pataha.variants]
  inherits = "ss04"

    [buildPlans.pataha.variants.design]
    f = "extended-crossbar-at-x-height"
    t = "cross"

    [buildPlans.pataha.variants.italic]
    f = "tailed"
    t = "flat-hook-short-neck2"

[buildPlans.pataha.widths.normal]
shape = 576
menu = 5
css = "normal"

  [buildPlans.pataha.slopes]
  upright = "normal"
  italic = "italic"
