name: Font build
on: 
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: 
      image: avivace/iosevka-build
      options: "--workdir /build"
      volumes:
        - ${{ github.workspace }}:/build
    
    env:
      FONT_VERSION: 4.1.1

    outputs:
      artifact-name: ${{ steps.set-artifact-name.outputs.artifact-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Chmod
        run: chmod +x /run.sh

      - name: Cache build source
        uses: actions/cache@v2
        with:
          path: /tmp/build/Iosevka${{ env.FONT_VERSION }}
          key: font-cache-${{ env.FONT_VERSION }}
          restore-keys: font-cache-

      - name: Build font
        run: /run.sh ttf::pataha
      
      - uses: actions/upload-artifact@v2
        with:
          name: font-binary
          path: ./dist
      
      - id: set-artifact-name
        run: echo "::set-output name=artifact-name::font-binary"
  
  release:
    name: Release
    needs: build
    runs-on: ubuntu-20.04

    steps: 
      - uses: actions/download-artifact@v2
        id: download
        with:
          name:  ${{ needs.build.outputs.artifact-name }}
          path: ./
      - name: Echo download path
        run: echo ${{ steps.download.outputs.download-path }}
      - name: Test
        run: ls -la
