name: Font build
on: 
  push:
    branches:
      - master

defaults:
  run:
    shell: bash
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: 
      image: avivace/iosevka-build
      options: "--workdir /build"
      volumes:
        - ${{ github.workspace }}:/build
    
    env:
      FONT_VERSION: 4.1.1

    # outputs:
    #   artifact-name: ${{ steps.set-artifact-name.outputs.artifact-name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build font
        run: /run ttf::pataha
        # with:
        #   args: ttf::pataha
      
      # - name: Test
      #   run: ls -la ./dist
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: ${{ matrix.workspace }}-${{ matrix.esphome }}-${{ matrix.esphome_board }}
      #     path: ${{ env.esphome_device_name }}/.pioenvs/${{ env.esphome_device_name }}/firmware.bin
      
      # - id: set-artifact-name
      #   run: echo "::set-output name=artifact-name::${{ matrix.workspace }}-${{ matrix.esphome }}-${{ matrix.esphome_board }}"
